version: '3.8'

services:
  acs-calculator:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    volumes:
      - .:/app
    restart: unless-stopped